batch_size: 128 # Default 128
epochs: 80 # Default 80
lr: 0.001 # Default 0.001

device: cuda:0 # Default 0
num_workers: 4 # Default 4
seed: 1234 # Default 1234
use_wandb: False # Default False

data_dir: data # Default data

# Evaluation
model_path: